server.port=8080
spring.application.name=hoteleria

# ========================================================
# Conexión a Base de Datos PostgreSQL (Contenedor Docker / Local)
# ========================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_princes_ica
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=hotel_user
spring.datasource.password=hotel_password_123

# JPA / Hibernate con PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Deshabilitar búsqueda de Consul Config si no hay servidor local
spring.cloud.consul.config.enabled=false
spring.cloud.consul.enabled=false

# Formato JSON Jackson
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=America/Lima

